"""Run every client against every case and diff the outcome with the expected matrix.

Usage: ``python -m clients.run_matrix [--clients naive,curl_cffi] [--cases a,b] [--no-diff]
[--output DIR]``. Writes ``RESULTS.md`` and ``results.json``; exits 1 on drift.
"""

from __future__ import annotations

import argparse
import importlib
import json
import sys
import time
from collections.abc import Callable
from pathlib import Path

from .common import CASES, CLIENTS, CaseResult, enable_all, reset_lab

HERE = Path(__file__).resolve().parent
EXPECTED_PATH = HERE / "expected_matrix.json"
MODULES = {
    "naive": "clients.naive_requests",
    "curl_cffi": "clients.curl_cffi_client",
    "playwright": "clients.playwright_client",
}


def _csv(value: str, allowed: list[str], what: str) -> list[str]:
    items = [v.strip() for v in value.split(",") if v.strip()]
    bad = [i for i in items if i not in allowed]
    if bad:
        raise SystemExit(f"unknown {what}: {', '.join(bad)} (choose from {', '.join(allowed)})")
    return items


def run_all(clients: list[str], cases: list[str]) -> list[CaseResult]:
    enable_all()
    results: list[CaseResult] = []
    for name in clients:
        reset_lab()
        run: Callable[[list[str]], list[CaseResult]] = importlib.import_module(MODULES[name]).run
        t0 = time.monotonic()
        part = run(cases)
        print(f"[{name}] {sum(r.passed for r in part)}/{len(part)} pass "
              f"({time.monotonic() - t0:.1f}s)", flush=True)
        results.extend(part)
    return results


def render_markdown(results: list[CaseResult], clients: list[str], cases: list[str]) -> str:
    by = {(r.client, r.case): r for r in results}
    mark = {True: "✅", False: "❌"}
    lines = ["# Lab results", "",
             "Generated by `python -m clients.run_matrix` (✅ = allowed, ❌ = blocked).", "",
             "| case | " + " | ".join(clients) + " |",
             "|---|" + "---|" * len(clients)]
    for case in cases:
        cells = [mark[by[(c, case)].passed] if (c, case) in by else "" for c in clients]
        lines.append(f"| {case} | " + " | ".join(cells) + " |")
    lines += ["", "## Signal reasons", "", "| case | client | verdict | score | reason |",
              "|---|---|---|---|---|"]
    for case in cases:
        for c in clients:
            r = by.get((c, case))
            if r:
                reason = r.reason.replace("|", "\\|")
                lines.append(f"| {case} | {c} | {r.verdict} | {r.score} | {reason} |")
    return "\n".join(lines) + "\n"


def diff_expected(results: list[CaseResult]) -> list[str]:
    expected: dict[str, dict[str, str]] = json.loads(EXPECTED_PATH.read_text())
    drift = []
    for r in results:
        want = expected.get(r.case, {}).get(r.client)
        got = "pass" if r.passed else "fail"
        if want is not None and want != got:
            drift.append(f"{r.case} x {r.client}: expected {want}, got {got} ({r.reason})")
    return drift


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--clients", default=",".join(CLIENTS))
    ap.add_argument("--cases", default=",".join(CASES))
    ap.add_argument("--no-diff", action="store_true", help="do not compare with expected matrix")
    ap.add_argument("--output", default=".", help="directory for RESULTS.md and results.json")
    args = ap.parse_args(argv)
    clients = _csv(args.clients, CLIENTS, "client")
    cases = _csv(args.cases, CASES, "case")

    start = time.monotonic()
    results = run_all(clients, cases)
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    (out / "RESULTS.md").write_text(render_markdown(results, clients, cases))
    (out / "results.json").write_text(
        json.dumps([r.to_dict() for r in results], indent=2, sort_keys=True) + "\n"
    )
    print(f"done in {time.monotonic() - start:.1f}s -> {out / 'RESULTS.md'}")
    if args.no_diff:
        return 0
    drift = diff_expected(results)
    for line in drift:
        print("DRIFT", line)
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
