"""Run every client against every case and diff the outcome with the expected matrix.

Usage: ``python -m clients.run_matrix [--clients naive,curl_cffi] [--cases a,b] [--no-diff]
[--output DIR]``. Writes ``RESULTS.md`` and ``results.json``; exits 1 on drift.

Every case is judged from the case's SIGNAL in the score report (``X-Lab-Report-Id`` ->
``GET /api/requests/{id}``), not from the HTTP status. A cell is ``pass`` (verdict pass or
skip), ``warn`` or ``fail`` (verdict fail or block). ``clients/expected_matrix.json`` stores
that class per cell; drift is any cell that differs.
"""

from __future__ import annotations

import argparse
import importlib
import json
import re
import sys
import time
from collections.abc import Callable
from pathlib import Path

from .common import (
    CASE_TABLE,
    CASES,
    CLIENTS,
    EXCLUDED,
    CaseResult,
    prepare_lab,
    reset_lab,
    restore_lab,
)

HERE = Path(__file__).resolve().parent
EXPECTED_PATH = HERE / "expected_matrix.json"
NOTES_PATH = HERE / "results_notes.md"
MODULES = {
    "naive": "clients.naive_requests",
    "curl_cffi": "clients.curl_cffi_client",
    "playwright": "clients.playwright_client",
}
MARK = {"pass": "✅", "warn": "⚠️", "fail": "❌"}


def _csv(value: str, allowed: list[str], what: str) -> list[str]:
    items = [v.strip() for v in value.split(",") if v.strip()]
    bad = [i for i in items if i not in allowed]
    if bad:
        raise SystemExit(f"unknown {what}: {', '.join(bad)} (choose from {', '.join(allowed)})")
    return items


def run_all(clients: list[str], cases: list[str]) -> list[CaseResult]:
    snapshot = prepare_lab()
    results: list[CaseResult] = []
    try:
        for name in clients:
            reset_lab()  # clients share one Docker bridge IP: keep ip_reputation per client
            run: Callable[[list[str]], list[CaseResult]] = importlib.import_module(
                MODULES[name]
            ).run
            t0 = time.monotonic()
            part = run(cases)
            counts = {c: sum(r.cell == c for r in part) for c in MARK}
            print(
                f"[{name}] pass={counts['pass']} warn={counts['warn']} fail={counts['fail']} "
                f"({time.monotonic() - t0:.1f}s)",
                flush=True,
            )
            results.extend(part)
    finally:
        restore_lab(snapshot)
    return results


def _stable(text: str) -> str:
    """Strip numbers that change from run to run so RESULTS.md stays byte-identical."""
    text = re.sub(r"\(\d+ ms old\)", "(N ms old)", text)
    return text.replace("|", "\\|")


def _by(results: list[CaseResult]) -> dict[tuple[str, str], CaseResult]:
    return {(r.client, r.case): r for r in results}


def render_markdown(results: list[CaseResult], clients: list[str], cases: list[str]) -> str:
    by = _by(results)
    lines = [
        "# Lab results",
        "",
        "Generated by `python -m clients.run_matrix` against the lab's own server. Each cell is "
        "judged from the case's signal in the score report, not from the HTTP status "
        "(✅ = verdict pass or skip, ⚠️ = warn, ❌ = fail or block).",
        "",
        "## Matrix",
        "",
        "| case | endpoint | " + " | ".join(clients) + " |",
        "|---|---|" + "---|" * len(clients),
    ]
    for case in cases:
        cells = [MARK[by[(c, case)].cell] if (c, case) in by else "" for c in clients]
        lines.append(f"| {case} | {CASE_TABLE[case].endpoint} | " + " | ".join(cells) + " |")
    lines += [
        "",
        "## Signal reasons",
        "",
        "`action/segment` is what the lab did with that request (the case's own signal is the "
        "only one evaluated on `/protected/<case>`, the other endpoint classes run every "
        "applicable module). `client` says what the client itself did.",
        "",
        "| case | client | cell | verdict | score | action/segment | reason | client |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for case in cases:
        for c in clients:
            r = by.get((c, case))
            if r:
                lines.append(
                    f"| {case} | {c} | {MARK[r.cell]} | {r.verdict} | {r.score} | "
                    f"{r.action}/{r.segment} | {_stable(r.reason)} | {_stable(r.note)} |"
                )
    lines += [
        "",
        "## Observed fingerprints",
        "",
        "| client | proto | JA4 | HTTP/2 | user agent |",
        "|---|---|---|---|---|",
    ]
    for c in clients:
        first = next((r for r in results if r.client == c and r.fingerprint), None)
        if first:
            fp = first.fingerprint
            lines.append(
                f"| {c} | {fp.get('proto', '')} | `{fp.get('ja4', '')}` | "
                f"`{fp.get('h2', '')}` | {first.user_agent} |"
            )
    lines += [
        "",
        "## Off by default (LOW confidence), excluded from the matrix",
        "",
        "| module | why it is not a case |",
        "|---|---|",
    ]
    for slug, why in EXCLUDED.items():
        lines.append(f"| {slug} | {why} |")
    text = "\n".join(lines) + "\n"
    if NOTES_PATH.exists() and cases == CASES and clients == CLIENTS:
        text += "\n" + NOTES_PATH.read_text()
    return text


def load_expected() -> dict[str, dict[str, str]]:
    data: dict[str, dict[str, str]] = json.loads(EXPECTED_PATH.read_text())
    return data


def diff_expected(results: list[CaseResult]) -> list[str]:
    expected = load_expected()
    drift = []
    for r in results:
        want = expected.get(r.case, {}).get(r.client)
        if want != r.cell:
            drift.append(
                f"{r.case} x {r.client}: expected {want}, got {r.cell} "
                f"({r.verdict} {r.score}: {r.reason})"
            )
    return drift


def expected_from(results: list[CaseResult], cases: list[str]) -> dict[str, dict[str, str]]:
    by = _by(results)
    out: dict[str, dict[str, str]] = {}
    for case in cases:
        row = {c: by[(c, case)].cell for c in CLIENTS if (c, case) in by}
        if row:
            out[case] = row
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--clients", default=",".join(CLIENTS))
    ap.add_argument("--cases", default=",".join(CASES))
    ap.add_argument("--no-diff", action="store_true", help="do not compare with expected matrix")
    ap.add_argument("--output", default=".", help="directory for RESULTS.md and results.json")
    ap.add_argument(
        "--write-expected",
        action="store_true",
        help="rewrite clients/expected_matrix.json from this run (full runs only)",
    )
    args = ap.parse_args(argv)
    clients = _csv(args.clients, CLIENTS, "client")
    cases = _csv(args.cases, CASES, "case")

    start = time.monotonic()
    results = run_all(clients, cases)
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    (out / "RESULTS.md").write_text(render_markdown(results, clients, cases))
    (out / "results.json").write_text(
        json.dumps([r.to_dict() for r in results], indent=2, sort_keys=True) + "\n"
    )
    print(f"done in {time.monotonic() - start:.1f}s -> {out / 'RESULTS.md'}")
    if args.write_expected:
        if cases != CASES or clients != CLIENTS:
            raise SystemExit("--write-expected needs a full run (all clients and cases)")
        EXPECTED_PATH.write_text(
            "{\n"
            + ",\n".join(
                f"  {json.dumps(case)}: {json.dumps(row)}"
                for case, row in expected_from(results, cases).items()
            )
            + "\n}\n"
        )
        print(f"wrote {EXPECTED_PATH}")
        return 0
    if args.no_diff:
        return 0
    drift = diff_expected(results)
    for line in drift:
        print("DRIFT", line)
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
